services:
  - type: web
    name: vocab-master
    env: python
    buildCommand: "./build.sh"
    startCommand: "pip install gunicorn && cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_VERSION
        value: 20.10.0
